---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v .
platforms:
  - name: etcd1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - etcd
  - name: etcd2
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    groups:
      - etcd
  - name: etcd3
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    groups:
      - etcd
provisioner:
  name: ansible
  # inventory:
  #   group_vars:
  #     etcd:
  #       etcd_download_url: ${MOLECULE_ETCD_DOWNLOAD_URL}
  config_options:
    defaults:
      verbosity: 2
verifier:
  name: ansible
