---
name: build
on: [push]
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      matrix:
        os: [centos7]
        scenario: [default]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible "molecule[docker,lint]"
          ansible-galaxy collection install -r requirements.yml
      - name: Test with molecule
        env:
          MOLECULE_DISTRO: ${{ matrix.os }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
        run: |
          cd ..
          ln -sf ansible-role-etcd etcd
          cd etcd
          molecule test --scenario-name ${MOLECULE_SCENARIO}
      - name: Publish role to Galaxy
        if: success()
        run: ansible-galaxy role import --branch main --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
